name: Test and build

on:
  push:
    branches: [ "front"]
  pull_request:
    branches: [ "front" ]

  workflow_dispatch:

env:
  DOCKER_USERNAME: nologin

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node 21
      
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud/polytech2024
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_API_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: rg.fr-par.scw.cloud/polytech-2024/noel/front:v1